const watchesData = [
    {
      id: 1,
      name: "Luna Smart Watch",
      description: "1.39\" HD Display | Limited Stock",
      price: 3999,
      originalPrice: 9999,
      discount: "70%.off",
      image: "https://zerolifestyle.co/cdn/shop/files/2_1.png?v=1725457585",
      colors: ["pink", "gray", "orange", "blue"],
      colorLabel: "pink",
    },
    {
      id: 2,
      name: "Ignite Smart Watch",
      description: "Up to 9 Days Battery | BT Calling",
      price: 3999,
      originalPrice: 9999,
      discount: "70%.off",
      image: "https://zerolifestyle.co/cdn/shop/files/Gold-01.webp?v=1722673246",
      colors: ["red", "yellow", "green", "blue"],
      colorLabel: "red",
    },
    {
      id: 3,
      name: "Glory SmartWatch",
      description: "Pakistan's First Curved Smartwatch",
      price: 3999,
      originalPrice: 9999,
      discount: "70%.off",
      image: "https://zerolifestyle.co/cdn/shop/files/Layer_4_B.webp?v=1719928924",
      colors: ["red", "yellow", "green", "purple"],
      colorLabel: "Aqua Green",
    },
    {
      id: 4,
      name: "Royale SmartWatch",
      description: "47% Faster ZEON Processor",
      price: 3999,
      originalPrice: 9999,
      discount: "70%.off",
      image: "https://zerolifestyle.co/cdn/shop/files/Royale_Black_0000_7f3352c3-7ebb-4e59-a97d-289e0b02857e.webp?v=1722258296",
      colors: ["red", "yellow", "cyan", "gray"],
      colorLabel: "Gray",
    },
    {
      id: 5,
      name: "Delta SmartWatch",
      description: "Largest 2.04\" Amoled Curved Display",
      price: 3999,
      originalPrice: 9999,
      discount: "70%.off",
      image: "https://zerolifestyle.co/cdn/shop/files/blackgold_3.png?v=1723061843",
      colors: ["pink", "yellow", "purple", "blue"],
      colorLabel: "Blue",
    },
  ];
  
  export default watchesData;
  